### ISSUE TITLE
hakchi 3.5.0

### ISSUE THREAD

**Issue by proudx2** [strikelight/Rebuild-XML#4]
I get the following message when trying to run the created xml file in hakchi 3.50 as filename  folders.xml when opening folder manager
XmlException
'quot' is an unexpected token. Expecting white space. Line 5027, position 60.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at com.clusterrr.hakchi_gui.FoldersManagerForm.XmlToTree(String xmlString)
   at com.clusterrr.hakchi_gui.FoldersManagerForm..ctor(NesMenuCollection nesMenuCollection, MainForm mainForm)
--- DEBUGLOG.TXT content ---
Base directory: G:\hackchi-without-games (portable mode)
Loading configuration
Starting, version: 3.5.0
Loading libretro core info files
Building libretro core cross index
Loading G:\hackchi-without-games\data\nescarts.xml
Loading G:\hackchi-without-games\data\snescarts.xml
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
[Upgrade] No upgrade action needed
...........................................Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Loading original games data
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
Local hakchi.hmod version info: boot 1.0.2, kernel 3.4.113.24-madmonkey, script v1.0.4-122
Saving selected games
Saving configuration
'quot' is an unexpected token. Expecting white space. Line 5027, position 60.   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at com.clusterrr.hakchi_gui.FoldersManagerForm.XmlToTree(String xmlString)
   at com.clusterrr.hakchi_gui.FoldersManagerForm..ctor(NesMenuCollection nesMenuCollection, MainForm mainForm)
--- End of DEBUGLOG.TXT content ---

**Comment by proudx2** [comment]
I figured it out. Had remove a rom with a quot in it from the list.
